import { existsSync, readdirSync } from 'node:fs';
import { defineConfig } from 'vite';

// Music keys that have a real file in public/assets/audio/music/. Anything else
// is generated by src/systems/Music.js (data/music.json). Read at build time,
// so a track needs no probing request: drop <key>.mp3 in and rebuild.
const musicDir = 'public/assets/audio/music';
const musicFiles = existsSync(musicDir)
  ? readdirSync(musicDir).filter((f) => f.endsWith('.mp3')).map((f) => f.slice(0, -4))
  : [];

export default defineConfig({
  base: './',
  define: { __MUSIC_FILES__: JSON.stringify(musicFiles) },
});
