import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { defineConfig } from 'vite';

// Music keys that have a real file in public/assets/audio/music/. Anything else
// is generated by src/systems/Music.js (data/music.json). Read at build time,
// so a track needs no probing request: drop <key>.mp3 in and rebuild.
const musicDir = 'public/assets/audio/music';
const musicFiles = existsSync(musicDir)
  ? readdirSync(musicDir).filter((f) => f.endsWith('.mp3')).map((f) => f.slice(0, -4))
  : [];

// Same for SFX: public/assets/audio/sfx/<name>.mp3 overrides the procedural
// recipe of that name in data/audio.json (no file = the recipe, or silence).
const sfxDir = 'public/assets/audio/sfx';
const sfxFiles = existsSync(sfxDir)
  ? readdirSync(sfxDir).filter((f) => f.endsWith('.mp3')).map((f) => f.slice(0, -4))
  : [];

// The game's version (package.json), shown on the Title and Menu (systems/Version.js).
const appVersion = JSON.parse(readFileSync('package.json', 'utf8')).version;

export default defineConfig({
  base: './',
  define: { __MUSIC_FILES__: JSON.stringify(musicFiles), __SFX_FILES__: JSON.stringify(sfxFiles), __APP_VERSION__: JSON.stringify(appVersion) },
});
