import audioData from '../data/audio.json';
import { MusicEngine, hasTrack } from './Music.js';

// One AudioContext for everything: procedural SFX (oscillator/noise
// envelopes from audio.json, no files) and music with a crossfade. A track
// plays from public/assets/audio/music/<key>.mp3 when that file exists
// (vite.config.js lists them at build time), otherwise it is generated by
// systems/Music.js from data/music.json. Everything goes through one master
// limiter and is suspended while the page is hidden.

let ctx = null;
let musicBus = null;
let sfxBus = null;
let volumes = { musicVolume: 1, sfxVolume: 1 };
let wantedMusic = null;
let master = null;
let musicEngine = null;
let current = null; // {key, stop(fadeSec), track?} — a decoded file or a procedural track
const musicState = { intensity: 0, warm: false };
const FILES = new Set(typeof __MUSIC_FILES__ !== 'undefined' ? __MUSIC_FILES__ : []);
const buffers = new Map(); // key -> Promise<AudioBuffer | null>
const bytes = new Map(); // key -> Promise<ArrayBuffer | null> (prefetched, not yet decoded)
let noiseBuffer = null;

export function unlockAudio() {
  if (!ctx) {
    const AudioContextClass = window.AudioContext || window.webkitAudioContext;
    if (!AudioContextClass) return null;
    ctx = new AudioContextClass();
    musicBus = ctx.createGain();
    sfxBus = ctx.createGain();
    // Master limiter: music + SFX never clip when they stack.
    master = ctx.createDynamicsCompressor();
    master.threshold.value = audioData.master.threshold;
    master.knee.value = audioData.master.knee;
    master.ratio.value = audioData.master.ratio;
    master.attack.value = audioData.master.attack;
    master.release.value = audioData.master.release;
    master.connect(ctx.destination);
    musicBus.connect(master);
    sfxBus.connect(master);
    applyVolumes();
    // iOS only unlocks after a sound starts inside the gesture.
    const silent = ctx.createBufferSource();
    silent.buffer = ctx.createBuffer(1, 1, 22050);
    silent.connect(ctx.destination);
    silent.start(0);
    document.addEventListener('visibilitychange', onVisibility);
    if (wantedMusic) playMusic(wantedMusic);
  }
  if (ctx.state === 'suspended' && document.visibilityState !== 'hidden') ctx.resume().catch(() => {});
  return ctx;
}

export function getAudioContext() {
  return ctx;
}

function onVisibility() {
  if (!ctx) return;
  if (document.visibilityState === 'hidden') ctx.suspend().catch(() => {});
  else ctx.resume().catch(() => {});
}

export function setVolumes(settings) {
  volumes = { musicVolume: settings.musicVolume, sfxVolume: settings.sfxVolume };
  applyVolumes();
}

function applyVolumes() {
  if (!ctx) return;
  musicBus.gain.value = volumes.musicVolume;
  sfxBus.gain.value = volumes.sfxVolume;
}

// ---------- Haptics ----------

// A short buzz where the browser supports it (Android; iOS ignores it).
// Off when the SFX volume is 0.
export function vibrate(ms) {
  if (!ms || volumes.sfxVolume <= 0) return;
  try {
    if (navigator.vibrate) navigator.vibrate(ms);
  } catch (err) {
    // not allowed here (e.g. no user gesture yet) — skip
  }
}

// ---------- SFX ----------

export function playSfx(name) {
  const layers = audioData.sfx[name];
  if (!ctx || !layers || ctx.state !== 'running') return;
  const now = ctx.currentTime;
  for (const layer of layers) {
    const start = now + (layer.delayMs || 0) / 1000;
    const end = start + layer.ms / 1000;
    const env = ctx.createGain();
    env.gain.setValueAtTime(layer.gain, start);
    env.gain.exponentialRampToValueAtTime(0.0001, end);
    env.connect(sfxBus);

    let source;
    if (layer.type === 'noise') {
      source = ctx.createBufferSource();
      source.buffer = getNoise();
      const filter = ctx.createBiquadFilter();
      filter.type = 'lowpass';
      filter.frequency.value = layer.filterHz;
      source.connect(filter);
      filter.connect(env);
    } else {
      source = ctx.createOscillator();
      source.type = layer.wave;
      source.frequency.setValueAtTime(layer.from, start);
      source.frequency.exponentialRampToValueAtTime(layer.to, end);
      source.connect(env);
    }
    source.start(start);
    source.stop(end + 0.02);
  }
}

// ---------- Dialogue voice blips ----------

let lastBlipAt = -Infinity;

// One short typewriter blip for a voice from voices.json:
// {wave, freq, slideTo?, durMs, jitter?, gain, lowpass?}. wave "noise" uses
// the shared noise buffer. Goes through the SFX bus, so the SFX volume
// setting applies. Does nothing while audio is locked/suspended, and at most
// one blip per audio.json blip.minGapMs.
export function playBlip(voice) {
  if (!voice || !ctx || ctx.state !== 'running') return;
  const nowMs = performance.now();
  if (nowMs - lastBlipAt < audioData.blip.minGapMs) return;
  lastBlipAt = nowMs;

  const start = ctx.currentTime;
  const end = start + voice.durMs / 1000;
  const env = ctx.createGain();
  env.gain.setValueAtTime(0.0001, start);
  env.gain.linearRampToValueAtTime(voice.gain, start + audioData.blip.attackMs / 1000);
  env.gain.exponentialRampToValueAtTime(0.0001, end);
  env.connect(sfxBus);

  let source;
  if (voice.wave === 'noise') {
    source = ctx.createBufferSource();
    source.buffer = getNoise();
  } else {
    const pitch = 1 + (Math.random() * 2 - 1) * (voice.jitter || 0);
    source = ctx.createOscillator();
    source.type = voice.wave;
    source.frequency.setValueAtTime(voice.freq * pitch, start);
    if (voice.slideTo) source.frequency.linearRampToValueAtTime(voice.slideTo * pitch, end);
  }
  if (voice.lowpass) {
    const filter = ctx.createBiquadFilter();
    filter.type = 'lowpass';
    filter.frequency.value = voice.lowpass;
    source.connect(filter);
    filter.connect(env);
  } else {
    source.connect(env);
  }
  source.start(start);
  source.stop(end + 0.02);
}

function getNoise() {
  if (!noiseBuffer) {
    noiseBuffer = ctx.createBuffer(1, ctx.sampleRate / 2, ctx.sampleRate);
    const data = noiseBuffer.getChannelData(0);
    for (let i = 0; i < data.length; i++) data[i] = Math.random() * 2 - 1;
  }
  return noiseBuffer;
}

// ---------- Music ----------

// The track for a scene key (audio.json music.scenes), if any.
export function playSceneMusic(sceneKey) {
  const key = audioData.music.scenes[sceneKey];
  if (key) playMusic(key);
}

// Crossfades to the track `key` (null = fade to silence). Asking for the
// track that is already playing does nothing.
export function playMusic(key) {
  wantedMusic = key;
  if (!ctx) return;
  if (current && current.key === key) return;

  const fade = audioData.music.crossfadeMs / 1000;
  if (current) {
    current.stop(fade);
    current = null;
  }
  // A new track starts plain; the scene asks for intensity / warmth again.
  musicState.intensity = 0;
  musicState.warm = false;
  if (!key) return;

  if (FILES.has(key)) startFile(key, fade);
  else startProcedural(key, fade);
}

// Procedural track from data/music.json (silence if the key has none).
function startProcedural(key, fade) {
  if (!hasTrack(key)) return;
  if (!musicEngine) musicEngine = new MusicEngine(ctx, musicBus);
  const track = musicEngine.play(key, fade);
  track.setIntensity(musicState.intensity);
  track.setWarm(musicState.warm);
  current = { key, track, stop: (f) => musicEngine.stop(track, f) };
}

function startFile(key, fade) {
  loadBuffer(key).then((buffer) => {
    if (wantedMusic !== key || (current && current.key === key)) return;
    // Listed but unreadable (bad file): use the generated track instead.
    if (!buffer) {
      startProcedural(key, fade);
      return;
    }
    const source = ctx.createBufferSource();
    source.buffer = buffer;
    source.loop = true;
    const gain = ctx.createGain();
    const now = ctx.currentTime;
    gain.gain.setValueAtTime(0, now);
    gain.gain.linearRampToValueAtTime(1, now + fade);
    source.connect(gain);
    gain.connect(musicBus);
    source.start(now);
    current = {
      key,
      stop: (f) => {
        const t = ctx.currentTime;
        gain.gain.setValueAtTime(gain.gain.value, t);
        gain.gain.linearRampToValueAtTime(0, t + f);
        source.stop(t + f + 0.05);
      },
    };
  });
}

// 0..1 — how hard the music plays (boss phase 2 adds its intensity layers).
// Remembered across tracks until the next call.
export function setMusicIntensity(value) {
  musicState.intensity = Math.max(0, Math.min(1, value));
  if (current && current.track) current.track.setIntensity(musicState.intensity);
}

// The warm major variant of the current track (the Recollection ultimate).
export function setMusicWarm(on) {
  musicState.warm = !!on;
  if (current && current.track) current.track.setWarm(musicState.warm);
}

// Perf script: forget the scheduler timings so far (the first ticks build buffers).
export function resetMusicStats() {
  if (musicEngine) musicEngine.stats = { notes: 0, dropped: 0, ticks: 0, tickMs: 0, maxTickMs: 0 };
}

// For the ?music= panel and the perf script.
export function musicStatus() {
  const track = current && current.track;
  return {
    key: current ? current.key : null,
    procedural: !!track,
    intensity: musicState.intensity,
    warm: musicState.warm,
    position: track ? track.position() : null,
    stats: musicEngine ? { ...musicEngine.stats } : null,
    audioTime: ctx ? ctx.currentTime : 0,
    state: ctx ? ctx.state : 'none',
  };
}

function loadBuffer(key) {
  if (!buffers.has(key)) {
    const promise = fetchBytes(key)
      .then((data) => (data ? decode(data) : null))
      .catch(() => null);
    buffers.set(key, promise);
  }
  return buffers.get(key);
}

function fetchBytes(key) {
  if (!bytes.has(key)) {
    const url = `${audioData.music.dir}${key}${audioData.music.ext}`;
    const promise = fetch(url)
      .then((res) => (res.ok && !/text\/html/.test(res.headers.get('content-type') || '') ? res.arrayBuffer() : null))
      .catch(() => null);
    bytes.set(key, promise);
  }
  return bytes.get(key);
}

// Downloads every music track (audio.json scenes + battles) in the
// background, one after another, so a track is ready when its scene starts.
// Decoding waits for playMusic (it needs the unlocked AudioContext).
export async function prefetchMusic(keys = audioData.music.prefetch) {
  for (const key of keys) if (FILES.has(key)) await fetchBytes(key);
}

// Safari's decodeAudioData still wants callbacks. A file that isn't audio
// (e.g. a dev server's HTML fallback) decodes to null = silence.
function decode(data) {
  return new Promise((resolve) => {
    try {
      const p = ctx.decodeAudioData(data, resolve, () => resolve(null));
      if (p && p.catch) p.catch(() => resolve(null));
    } catch (err) {
      resolve(null);
    }
  });
}
