import audioData from '../data/audio.json';
import { MusicEngine, hasTrack } from './Music.js';

// One AudioContext for everything: procedural SFX (oscillator/noise
// envelopes from audio.json, no files) and music with a crossfade. A track
// plays from public/assets/audio/music/<key>.mp3 when that file exists
// (vite.config.js lists them at build time), otherwise it is generated by
// systems/Music.js from data/music.json. Everything goes through one master
// limiter and is suspended while the page is hidden.

let ctx = null;
let musicBus = null;
let sfxBus = null;
let volumes = { musicVolume: 1, sfxVolume: 1 };
let paused = false; // the pause menu is up: music ducks, SFX are silent
let wantedMusic = null;
let master = null;
let musicEngine = null;
let current = null; // {key, stop(fadeSec), track?} — a decoded file or a procedural track
const musicState = { intensity: 0, warm: false };
const FILES = new Set(typeof __MUSIC_FILES__ !== 'undefined' ? __MUSIC_FILES__ : []);
const SFX_FILES = new Set(typeof __SFX_FILES__ !== 'undefined' ? __SFX_FILES__ : []);
const sfxDecoded = new Map(); // name -> AudioBuffer (decoded, ready to play at once)
const buffers = new Map(); // key -> Promise<AudioBuffer | null>
const bytes = new Map(); // key -> Promise<ArrayBuffer | null> (prefetched, not yet decoded)
let noiseBuffer = null;

export function unlockAudio() {
  if (!ctx) {
    const AudioContextClass = window.AudioContext || window.webkitAudioContext;
    if (!AudioContextClass) return null;
    ctx = new AudioContextClass();
    musicBus = ctx.createGain();
    sfxBus = ctx.createGain();
    // Master limiter: music + SFX never clip when they stack.
    master = ctx.createDynamicsCompressor();
    master.threshold.value = audioData.master.threshold;
    master.knee.value = audioData.master.knee;
    master.ratio.value = audioData.master.ratio;
    master.attack.value = audioData.master.attack;
    master.release.value = audioData.master.release;
    master.connect(ctx.destination);
    musicBus.connect(master);
    sfxBus.connect(master);
    applyVolumes();
    warmSfx();
    document.addEventListener('visibilitychange', onVisibility);
    // Whenever the context (re)starts running, make sure the wanted music is
    // actually playing: the first gesture can resolve resume() a beat late.
    ctx.onstatechange = onStateChange;
    if (wantedMusic) applyMusic(wantedMusic);
    if (wantedAmbience) startAmbience(wantedAmbience, audioData.ambience.beds[wantedAmbience]);
  }
  // Not running yet (first gesture), or 'interrupted' (iOS: a call, Siri, an
  // app switch): resume inside this gesture. iOS also wants a sound started
  // inside the gesture before it lets the context run.
  if (ctx.state !== 'running' && document.visibilityState !== 'hidden') {
    try {
      const silent = ctx.createBufferSource();
      silent.buffer = ctx.createBuffer(1, 1, 22050);
      silent.connect(ctx.destination);
      silent.start(0);
    } catch (err) {
      // nothing to do: resume() below is the real unlock
    }
    ctx.resume().catch(() => {});
  }
  return ctx;
}

function onStateChange() {
  if (!ctx || ctx.state !== 'running') return;
  if (wantedMusic && !current) applyMusic(wantedMusic);
  if (wantedAmbience && !ambience) startAmbience(wantedAmbience, audioData.ambience.beds[wantedAmbience]);
}

// Document-level gesture hooks (called once from main.js): every pointerdown
// and touchend (capture, passive, so nothing can stop them) creates/resumes
// the context. iOS counts touchend (not always pointerdown) as the gesture
// that may start audio; 'interrupted' (iOS: a call, Siri) is resumed too.
let listening = false;
export function installAudioUnlock() {
  if (listening || typeof document === 'undefined') return;
  listening = true;
  const opts = { capture: true, passive: true };
  const handler = () => {
    if (ctx && ctx.state === 'running') return;
    unlockAudio();
  };
  document.addEventListener('pointerdown', handler, opts);
  document.addEventListener('touchend', handler, opts);
}

export function getAudioContext() {
  return ctx;
}

function onVisibility() {
  if (!ctx) return;
  if (document.visibilityState === 'hidden') ctx.suspend().catch(() => {});
  else ctx.resume().catch(() => {});
}

export function setVolumes(settings) {
  volumes = { musicVolume: settings.musicVolume, sfxVolume: settings.sfxVolume };
  applyVolumes();
}

function applyVolumes() {
  if (!ctx) return;
  // audio.json music.gain: a global trim under the Settings volume (Kostas: all music -10 %).
  musicBus.gain.value = volumes.musicVolume * (audioData.music.gain ?? 1) * (paused ? audioData.pause.musicDuck : 1);
  sfxBus.gain.value = paused ? 0 : volumes.sfxVolume;
}

// The game is paused (pause menu): music ducks to audio.json pause.musicDuck,
// SFX (and the ambience beds on that bus) go quiet until resume.
export function setAudioPaused(on) {
  paused = !!on;
  applyVolumes();
}

// ---------- Haptics ----------

// A short buzz where the browser supports it (Android; iOS ignores it).
// `ms` is a number or a pattern [buzz, gap, buzz, ...] (impact.json haptic).
// Off when the SFX volume is 0.
export function vibrate(ms) {
  if (!ms || (Array.isArray(ms) && !ms.length) || volumes.sfxVolume <= 0) return;
  try {
    if (navigator.vibrate) navigator.vibrate(ms);
  } catch (err) {
    // not allowed here (e.g. no user gesture yet) — skip
  }
}

// ---------- SFX ----------

// A file public/assets/audio/sfx/<name>.mp3 (listed at build time, __SFX_FILES__)
// wins over the procedural recipe audio.json sfx[name]; with neither it is silent.
// A file that is not decoded yet plays the recipe (if any) this once, so a
// sound never arrives late.
// `name` may be a list of names (a shot or line with several cues): all play at once.
// opts.pitch (default 1) multiplies the frequency of a procedural recipe's oscillator layers.
export function playSfx(name, opts = {}) {
  const pitch = opts.pitch ?? 1;
  if (Array.isArray(name)) {
    name.forEach((n) => playSfx(n));
    return;
  }
  audioLog(opts.pitch === undefined ? { ev: 'sfx', name } : { ev: 'sfx', name, pitch });
  if (!ctx || ctx.state !== 'running') return;
  const layers = audioData.sfx[name];
  const gain = audioData.sfxGain?.[name] ?? 1;
  if (SFX_FILES.has(name)) {
    const buffer = sfxDecoded.get(name);
    if (buffer) {
      playBuffer(buffer, gain, name);
      return;
    }
    const pending = loadSfx(name);
    if (layers && layers.length) playLayers(layers, sfxBus, pitch);
    else pending.then((b) => b && ctx && ctx.state === 'running' && playBuffer(b, gain, name));
    return;
  }
  if (layers) playLayers(layers, sfxBus, pitch);
}

// File SFX that are playing: {name, source, gain} (stopAllSfx fades them out).
const activeSfx = new Set();

function playBuffer(buffer, gain = 1, name = null) {
  const source = ctx.createBufferSource();
  source.buffer = buffer;
  const g = ctx.createGain();
  g.gain.value = gain;
  source.connect(g);
  g.connect(sfxBus);
  const rec = { name, source, gain: g };
  activeSfx.add(rec);
  source.onended = () => activeSfx.delete(rec);
  source.start();
}

// Fades out the playing file SFX over fadeMs and stops them (a skipped cutscene, a scene that
// ends, a long cue at the next shot). `names` limits it to those cues (audio.json sfxLong has the
// long ones); without it every file SFX goes. Procedural SFX are short and left alone.
export function stopAllSfx(fadeMs = 400, names = null) {
  audioLog({ ev: 'stopSfx', names, fadeMs });
  if (!ctx) return;
  const t = ctx.currentTime;
  for (const rec of [...activeSfx]) {
    if (names && !names.includes(rec.name)) continue;
    activeSfx.delete(rec);
    rec.gain.gain.setValueAtTime(rec.gain.gain.value, t);
    rec.gain.gain.linearRampToValueAtTime(0, t + fadeMs / 1000);
    try {
      rec.source.stop(t + fadeMs / 1000 + 0.05);
    } catch (err) {
      // already ended
    }
  }
}

// Decodes (once) the file of an SFX; resolves null when it cannot be had.
function loadSfx(name) {
  return loadBuffer(`sfx/${name}`, audioData.sfxFiles).then((buffer) => {
    if (buffer) sfxDecoded.set(name, buffer);
    return buffer;
  });
}

// Right after unlock: decode every SFX file (their bytes are prefetched in the background).
function warmSfx() {
  for (const name of SFX_FILES) loadSfx(name);
}

// Downloads the SFX files in the background (after the music), decoded after unlock.
export async function prefetchSfx() {
  for (const name of SFX_FILES) await fetchBytes(`sfx/${name}`, audioData.sfxFiles);
}

// One-shot envelope layers (the audio.json sfx format) into `dest`.
function playLayers(layers, dest, pitch = 1) {
  const now = ctx.currentTime;
  for (const layer of layers) {
    const start = now + (layer.delayMs || 0) / 1000;
    const end = start + layer.ms / 1000;
    const env = ctx.createGain();
    if (layer.attackMs) {
      // A swell: up to the gain over attackMs, then the usual decay.
      const peak = Math.min(end - 0.001, start + layer.attackMs / 1000);
      env.gain.setValueAtTime(0.0001, start);
      env.gain.linearRampToValueAtTime(layer.gain, peak);
    } else {
      env.gain.setValueAtTime(layer.gain, start);
    }
    env.gain.exponentialRampToValueAtTime(0.0001, end);
    env.connect(dest);

    let source;
    if (layer.type === 'noise') {
      source = ctx.createBufferSource();
      source.buffer = getNoise();
      const filter = ctx.createBiquadFilter();
      filter.type = layer.filter || 'lowpass';
      filter.frequency.value = layer.filterHz;
      source.connect(filter);
      filter.connect(env);
    } else {
      source = ctx.createOscillator();
      source.type = layer.wave;
      source.frequency.setValueAtTime(layer.from * pitch, start);
      source.frequency.exponentialRampToValueAtTime(layer.to * pitch, end);
      source.connect(env);
    }
    source.start(start);
    source.stop(end + 0.02);
  }
}

// ---------- Dialogue voice blips ----------

let lastBlipAt = -Infinity;

// One short typewriter blip for a voice from voices.json:
// {wave, freq, slideTo?, durMs, jitter?, gain, lowpass?}. wave "noise" uses
// the shared noise buffer. Goes through the SFX bus, so the SFX volume
// setting applies. Does nothing while audio is locked/suspended, and at most
// one blip per audio.json blip.minGapMs.
export function playBlip(voice) {
  if (!voice || !ctx || ctx.state !== 'running') return;
  const nowMs = performance.now();
  if (nowMs - lastBlipAt < audioData.blip.minGapMs) return;
  lastBlipAt = nowMs;

  const start = ctx.currentTime;
  const end = start + voice.durMs / 1000;
  const env = ctx.createGain();
  env.gain.setValueAtTime(0.0001, start);
  env.gain.linearRampToValueAtTime(voice.gain, start + audioData.blip.attackMs / 1000);
  env.gain.exponentialRampToValueAtTime(0.0001, end);
  env.connect(sfxBus);

  let source;
  if (voice.wave === 'noise') {
    source = ctx.createBufferSource();
    source.buffer = getNoise();
  } else {
    const pitch = 1 + (Math.random() * 2 - 1) * (voice.jitter || 0);
    source = ctx.createOscillator();
    source.type = voice.wave;
    source.frequency.setValueAtTime(voice.freq * pitch, start);
    if (voice.slideTo) source.frequency.linearRampToValueAtTime(voice.slideTo * pitch, end);
  }
  if (voice.lowpass) {
    const filter = ctx.createBiquadFilter();
    filter.type = 'lowpass';
    filter.frequency.value = voice.lowpass;
    source.connect(filter);
    filter.connect(env);
  } else {
    source.connect(env);
  }
  source.start(start);
  source.stop(end + 0.02);
}

// ---------- Ambience ----------

// A looping bed from audio.json ambience.beds (rain, city, office…): noise
// through filters and/or a low tone, each with a slow gain wobble. One bed at
// a time; playAmbience(null) fades it out. Goes through the SFX bus.
let ambience = null; // {key, nodes: [], gain}

export function playAmbience(key) {
  if (ambience && ambience.key === key) return;
  stopAmbience();
  const layers = key && audioData.ambience.beds[key];
  if (!layers) return;
  wantedAmbience = key;
  if (!ctx) return;
  startAmbience(key, layers);
}

let wantedAmbience = null;

// A bed is a list of looping layers, or {layers, events}: events are
// one-shots in the sfx format ({sound, everyMs: [min, max]}) that fire at
// random intervals (a distant drum, a gavel), through the bed's own fade.
function startAmbience(key, bed) {
  const layers = Array.isArray(bed) ? bed : bed.layers;
  const fade = audioData.ambience.fadeMs / 1000;
  const now = ctx.currentTime;
  const out = ctx.createGain();
  out.gain.setValueAtTime(0, now);
  out.gain.linearRampToValueAtTime(1, now + fade);
  out.connect(sfxBus);
  const nodes = [out];
  for (const layer of layers) {
    const g = ctx.createGain();
    g.gain.value = layer.gain;
    g.connect(out);
    let source;
    let tail = g;
    if (layer.type === 'noise') {
      source = ctx.createBufferSource();
      source.buffer = getNoise();
      source.loop = true;
      const lp = ctx.createBiquadFilter();
      lp.type = 'lowpass';
      lp.frequency.value = layer.filterHz;
      tail = lp;
      lp.connect(g);
      if (layer.highpassHz) {
        const hp = ctx.createBiquadFilter();
        hp.type = 'highpass';
        hp.frequency.value = layer.highpassHz;
        hp.connect(lp);
        tail = hp;
      }
      source.connect(tail);
    } else {
      source = ctx.createOscillator();
      source.type = layer.wave;
      source.frequency.value = layer.hz;
      source.connect(g);
    }
    if (layer.wobble) {
      const lfo = ctx.createOscillator();
      lfo.frequency.value = 1000 / layer.wobble.periodMs;
      const depth = ctx.createGain();
      depth.gain.value = layer.gain * layer.wobble.depth;
      lfo.connect(depth);
      depth.connect(g.gain);
      lfo.start(now);
      nodes.push(lfo);
    }
    source.start(now, layer.type === 'noise' ? Math.random() * 0.8 : 0);
    nodes.push(source);
  }
  const current = { key, nodes, gain: out, timers: [] };
  ((!Array.isArray(bed) && bed.events) || []).forEach((event, i) => {
    const next = () => {
      const [min, max] = event.everyMs;
      const id = setTimeout(() => {
        if (ambience !== current) return;
        if (ctx.state === 'running' && !paused) playLayers(event.sound, out);
        next();
      }, min + Math.random() * (max - min));
      current.timers[i] = id;
    };
    next();
  });
  ambience = current;
}

export function stopAmbience() {
  wantedAmbience = null;
  if (!ambience) return;
  const { nodes, gain, timers } = ambience;
  ambience = null;
  for (const id of timers || []) clearTimeout(id);
  if (!ctx) return;
  const fade = audioData.ambience.fadeMs / 1000;
  const t = ctx.currentTime;
  gain.gain.setValueAtTime(gain.gain.value, t);
  gain.gain.linearRampToValueAtTime(0, t + fade);
  for (const n of nodes) {
    if (n.stop) {
      try {
        n.stop(t + fade + 0.05);
      } catch (err) {
        // already stopped
      }
    }
  }
}

function getNoise() {
  if (!noiseBuffer) {
    noiseBuffer = ctx.createBuffer(1, ctx.sampleRate / 2, ctx.sampleRate);
    const data = noiseBuffer.getChannelData(0);
    for (let i = 0; i < data.length; i++) data[i] = Math.random() * 2 - 1;
  }
  return noiseBuffer;
}

// ---------- Music ----------

// Keys: a music key is a file (public/assets/audio/music/<key>.mp3), a procedural track
// of that name (data/music.json), or an alias (audio.json music.aliases, one hop) for
// another key. A track loops unless audio.json music.loop[key] is false. One-shots
// (playOneShot) duck the music under them. Which scene plays what is data too
// (music.scenes, music.placement); the scenes call these functions.

const mcfg = audioData.music;
let oneShot = null; // {key, id, resume, stop(fadeSec)} — a jingle / stinger / cue over the music
let quietUntil = 0; // performance.now() before which no new music starts (musicSilence)
let pendingPlay = null; // timer of a playMusic held back by musicSilence
let duckLevel = 1; // the gain a resume one-shot holds the music at (a track still loading starts at it)
// One looping file track at a time: every live music source (playing or fading out) is in this set, a new
// track stops whatever else is still sounding, and a request for the track that is playing, or that is
// already decoding, does nothing (no second source, no restart).
const musicSources = new Set();
let pendingStart = null; // {id}: the file track whose decode a start is waiting for

// Dev / QA only: window.__audio (scripts/qa/lib.mjs) collects every music request,
// so a headless run can assert the play/stop sequence. Nothing happens in the game.
// Every build also keeps the last RECENT_MAX music events (not SFX) for musicDiagnostics().
const RECENT_MAX = 60;
const recentMusic = [];
function audioLog(entry) {
  const row = { t: Math.round(performance.now()), ...entry };
  if (!String(entry.ev).startsWith('sfx') && entry.ev !== 'stopSfx') {
    recentMusic.push(row);
    if (recentMusic.length > RECENT_MAX) recentMusic.shift();
  }
  try {
    const hook = window.__audio;
    if (hook) (hook.log || (hook.log = [])).push(row);
  } catch (err) {
    // no window / blocked: skip
  }
}

// alias -> the key it stands for (one hop).
export function resolveMusicKey(key) {
  return (key && mcfg.aliases[key]) || key;
}

const isLoop = (key) => mcfg.loop[key] !== false;

// The track for a scene key (audio.json music.scenes), if any.
export function playSceneMusic(sceneKey) {
  const key = mcfg.scenes[sceneKey];
  if (key) playMusic(key);
  // The scene's ambience bed (audio.json music.ambience), none by default.
  if (sceneKey in mcfg.ambience) playAmbience(mcfg.ambience[sceneKey]);
}

// Crossfades to the track `key` (null = fade to silence). Asking for the
// track that is already playing does nothing (a ducked one comes back up).
// opts.crossfadeMs overrides audio.json music.crossfadeMs for this one change (placement entries {track, crossfadeMs}).
let fadeOverrideMs = null;
export function playMusic(key, opts) {
  fadeOverrideMs = opts && Number.isFinite(opts.crossfadeMs) ? opts.crossfadeMs : null;
  const id = resolveMusicKey(key);
  audioLog(key ? { ev: 'play', key, id, same: !!(current && current.id === id && !current.ended) } : { ev: 'stop', key: wantedMusic });
  applyMusic(key);
}

// playMusic without the log: also what the unlock / a held-back request calls to (re)start the wanted track.
function applyMusic(key) {
  const id = resolveMusicKey(key);
  wantedMusic = key;
  if (pendingPlay) {
    clearTimeout(pendingPlay);
    pendingPlay = null;
  }
  // musicSilence: a quiet gap is under way, the track starts when it is over.
  const wait = quietUntil - performance.now();
  if (key && wait > 0) {
    pendingPlay = setTimeout(() => {
      pendingPlay = null;
      if (wantedMusic === key) applyMusic(key);
    }, wait);
    return;
  }
  if (!ctx) return;
  const fade = (fadeOverrideMs ?? mcfg.crossfadeMs) / 1000;
  if (oneShot) endOneShot(fade);
  if (current && current.id === id && !current.ended) {
    current.setDuck(1, mcfg.oneShot.duckMs / 1000);
    return;
  }
  // The same file is already on its way (decoding): nothing to start twice.
  if (key && pendingStart && pendingStart.id === id) return;
  pendingStart = null;
  if (current) {
    current.stop(fade);
    current = null;
  }
  // A new track starts plain; the scene asks for intensity / warmth again.
  musicState.intensity = 0;
  musicState.warm = false;
  if (!key) return;

  if (FILES.has(id)) startFile(key, id, fade);
  else startProcedural(key, id, fade);
}

// Fade to silence and keep it quiet for `ms`: whatever playMusic asks for in that
// window starts when it is over (the gap after the Keepsake line).
export function musicSilence(ms) {
  audioLog({ ev: 'silence', ms });
  playMusic(null);
  quietUntil = performance.now() + ms;
}

// A jingle, stinger or cue (key: a file with loop false, or a procedural oneShot track) over
// the music. resume true: the music ducks to `duck` (over music.oneShot.duckMs) and comes back
// when the one-shot ends. resume false: the music fades out and stays silent afterwards.
export function playOneShot(key, { duck = mcfg.oneShot.duck, resume = true } = {}) {
  const id = resolveMusicKey(key);
  audioLog({ ev: 'oneshot', key, id, duck, resume });
  const fade = (fadeOverrideMs ?? mcfg.crossfadeMs) / 1000;
  if (oneShot) endOneShot(fade);
  const rec = { key, id, resume, stop: null };
  oneShot = rec;
  if (!resume) wantedMusic = null;
  if (!ctx) return;

  if (resume) duckLevel = duck;
  if (current) {
    if (resume) current.setDuck(duck, mcfg.oneShot.duckMs / 1000);
    else {
      current.stop(fade);
      current = null;
    }
  }
  const done = () => {
    if (oneShot !== rec) return;
    oneShot = null;
    duckLevel = 1;
    audioLog({ ev: 'oneshot_end', key });
    if (resume && current) current.setDuck(1, mcfg.oneShot.restoreMs / 1000);
  };
  if (FILES.has(id)) {
    loadBuffer(id).then((buffer) => {
      if (oneShot !== rec) return;
      if (!buffer) {
        done();
        return;
      }
      const source = ctx.createBufferSource();
      source.buffer = buffer;
      const gain = ctx.createGain();
      source.connect(gain);
      gain.connect(musicBus);
      source.onended = done;
      source.start();
      rec.stop = (f) => {
        const t = ctx.currentTime;
        gain.gain.setValueAtTime(gain.gain.value, t);
        gain.gain.linearRampToValueAtTime(0, t + f);
        try {
          source.stop(t + f + 0.05);
        } catch (err) {
          // already ended
        }
      };
    });
  } else if (hasTrack(id)) {
    if (!musicEngine) musicEngine = new MusicEngine(ctx, musicBus);
    const track = musicEngine.play(id, 0.05);
    track.onEnd = done;
    rec.stop = (f) => musicEngine.stop(track, f);
  } else {
    done();
  }
}

// Cuts the running one-shot (fading over fadeSec); the ducked music is not restored here.
function endOneShot(fadeSec) {
  const rec = oneShot;
  if (!rec) return;
  oneShot = null;
  duckLevel = 1;
  audioLog({ ev: 'oneshot_stop', key: rec.key });
  if (rec.stop) rec.stop(fadeSec);
}

// Procedural track from data/music.json (silence if the key has none).
function startProcedural(key, id, fade) {
  if (!hasTrack(id)) return;
  if (!musicEngine) musicEngine = new MusicEngine(ctx, musicBus);
  const track = musicEngine.play(id, fade);
  track.setIntensity(musicState.intensity);
  track.setWarm(musicState.warm);
  const rec = { key, id, ended: false, track, setDuck: (level, sec) => track.setDuck(level, sec), duckValue: () => track.duckGain.gain.value, stop: (f) => musicEngine.stop(track, f) };
  track.onEnd = () => {
    rec.ended = true;
  };
  current = rec;
  if (duckLevel !== 1) rec.setDuck(duckLevel, 0.05);
}

// Where a looping file track repeats: music.loopPoints[key] = [startSec, endSec] when set, else the
// decoded buffer without its silent ends (encoder delay at the start, padding / silence at the end):
// the first and the last sample above LOOP_FLOOR within LOOP_SCAN_SEC of either end.
const LOOP_FLOOR = 0.001; // -60 dB
const LOOP_MIN_TRIM_SEC = 0.005; // a trim shorter than this keeps the whole-buffer loop
const LOOP_SCAN_SEC = 0.2;
const loopCache = new WeakMap();
function loopRange(key, buffer) {
  const set = mcfg.loopPoints?.[key];
  if (set) return set;
  if (loopCache.has(buffer)) return loopCache.get(buffer);
  const rate = buffer.sampleRate;
  const scan = Math.min(buffer.length, Math.floor(LOOP_SCAN_SEC * rate));
  const channels = Array.from({ length: buffer.numberOfChannels }, (_, c) => buffer.getChannelData(c));
  let first = 0;
  search: for (let i = 0; i < scan; i++) {
    for (const d of channels) {
      if (Math.abs(d[i]) > LOOP_FLOOR) {
        first = i;
        break search;
      }
    }
  }
  let last = buffer.length;
  search: for (let i = buffer.length - 1; i >= buffer.length - scan; i--) {
    for (const d of channels) {
      if (Math.abs(d[i]) > LOOP_FLOOR) {
        last = i + 1;
        break search;
      }
    }
  }
  const range = last > first ? [first / rate, last / rate] : [0, buffer.duration];
  loopCache.set(buffer, range);
  return range;
}

function startFile(key, id, fade) {
  const ticket = { id };
  pendingStart = ticket;
  loadBuffer(id).then((buffer) => {
    // Only the latest request starts (a newer playMusic, a stop or a silence replaced this one meanwhile).
    if (pendingStart !== ticket || wantedMusic !== key) return;
    pendingStart = null;
    if (current && current.id === id && !current.ended) return;
    // Listed but unreadable (bad file): use the generated track instead.
    if (!buffer) {
      startProcedural(key, id, fade);
      return;
    }
    const looping = isLoop(key);
    // A looping track is one source on a seamless loop (loopRange); a one-shot (music.loop[key] false) plays once.
    // Loop points are set only when they trim something audible-length (LOOP_MIN_TRIM_SEC); otherwise the
    // source loops the whole buffer (loopStart = loopEnd = 0), the path every browser handles.
    const makeSource = () => {
      const s = ctx.createBufferSource();
      s.buffer = buffer;
      s.loop = looping;
      if (looping) {
        const [from, to] = loopRange(key, buffer);
        if (from > LOOP_MIN_TRIM_SEC || buffer.duration - to > LOOP_MIN_TRIM_SEC) {
          s.loopStart = from;
          s.loopEnd = Math.min(to, buffer.duration);
        }
      }
      return s;
    };
    const source = makeSource();
    const gain = ctx.createGain();
    const duckNode = ctx.createGain();
    const now = ctx.currentTime;
    gain.gain.setValueAtTime(0, now);
    gain.gain.linearRampToValueAtTime(1, now + fade);
    source.connect(gain);
    gain.connect(duckNode);
    duckNode.connect(musicBus);
    const rec = {
      key,
      id,
      ended: false,
      stopping: false,
      source,
      startedAt: now,
      duckValue: () => duckNode.gain.value,
      setDuck: (level, sec) => {
        const t = ctx.currentTime;
        duckNode.gain.cancelScheduledValues(t);
        duckNode.gain.setValueAtTime(duckNode.gain.value, t);
        duckNode.gain.linearRampToValueAtTime(level, t + sec);
      },
      stop: (f) => {
        rec.stopping = true;
        const t = ctx.currentTime;
        gain.gain.cancelScheduledValues(t);
        gain.gain.setValueAtTime(gain.gain.value, t);
        gain.gain.linearRampToValueAtTime(0, t + f);
        try {
          rec.source.stop(t + f + 0.05);
        } catch (err) {
          // already ended
        }
      },
    };
    // A second sounding track must never happen: stop whatever is still up (it is faded, not left running).
    for (const other of musicSources) {
      if (other.stopping) continue;
      console.warn(`music: "${key}" starts while "${other.key}" is still playing; stopping it`);
      other.stop(fade);
    }
    musicSources.add(rec);
    // Safety net: a looping track that ends while it is still the wanted one (a browser that drops the
    // loop) starts again at once from its loop point, on the same gain chain, so the music never stops.
    const onEnded = (ended) => () => {
      if (ended !== rec.source) return;
      if (looping && !rec.stopping && current === rec && ctx) {
        const again = makeSource();
        again.connect(gain);
        again.onended = onEnded(again);
        rec.source = again;
        again.start(ctx.currentTime, again.loopStart || 0);
        audioLog({ ev: 'loop-restart', key });
        return;
      }
      audioLog({ ev: 'ended', key, stopping: rec.stopping, current: current === rec });
      rec.ended = true;
      musicSources.delete(rec);
      try {
        ended.disconnect();
        gain.disconnect();
        duckNode.disconnect();
      } catch (err) {
        // already disconnected
      }
    };
    source.onended = onEnded(source);
    source.start(now);
    current = rec;
    if (duckLevel !== 1) rec.setDuck(duckLevel, 0.05);
  });
}

// 0..1 — how hard the music plays (boss phase 2 adds its intensity layers).
// Remembered across tracks until the next call.
export function setMusicIntensity(value) {
  musicState.intensity = Math.max(0, Math.min(1, value));
  if (current && current.track) current.track.setIntensity(musicState.intensity);
}

// The warm major variant of the current track (the Recollection ultimate).
export function setMusicWarm(on) {
  musicState.warm = !!on;
  if (current && current.track) current.track.setWarm(musicState.warm);
}

// Perf script: forget the scheduler timings so far (the first ticks build buffers).
export function resetMusicStats() {
  if (musicEngine) musicEngine.stats = { notes: 0, dropped: 0, ticks: 0, tickMs: 0, maxTickMs: 0 };
}

// Field diagnostics (window.unrememberedMusic() in the browser console, set in main.js): what the
// music is doing right now and the last music events, to paste into a bug report.
export function musicDiagnostics() {
  return {
    wanted: wantedMusic,
    visibility: typeof document !== 'undefined' ? document.visibilityState : null,
    status: musicStatus(),
    recent: recentMusic.map((r) => ({ ...r })),
  };
}

// QA only (scripts/qa/music-loop.mjs): the live file source, to prove the loop safety net.
export function musicSourceForQa() {
  return current && current.source ? current.source : null;
}

// For the ?music= panel and the perf script.
export function musicStatus() {
  const track = current && current.track;
  return {
    key: current ? current.key : null,
    id: current ? current.id : null,
    oneShot: oneShot ? oneShot.key : null,
    sources: musicSources.size, // file tracks sounding (a fading-out one counts until it has ended)
    duck: current ? current.duckValue() : null,
    procedural: !!track,
    intensity: musicState.intensity,
    warm: musicState.warm,
    position: track ? track.position() : null,
    stats: musicEngine ? { ...musicEngine.stats } : null,
    audioTime: ctx ? ctx.currentTime : 0,
    state: ctx ? ctx.state : 'none',
    ambience: ambience ? ambience.key : null,
    sfxPlaying: activeSfx.size,
    file: current && current.source ? { loop: current.source.loop, loopStart: current.source.loopStart, loopEnd: current.source.loopEnd, duration: current.source.buffer.duration, elapsed: ctx.currentTime - current.startedAt, ended: current.ended } : null,
    resident: [...buffers.keys()].filter((k) => !k.startsWith('sfx/')),
  };
}

function loadBuffer(key, source = audioData.music) {
  if (!buffers.has(key)) {
    if (!ctx) return Promise.resolve(null);
    const promise = fetchBytes(key, source)
      .then((data) => (data ? decode(data) : null))
      .catch(() => null);
    buffers.set(key, promise);
  }
  return buffers.get(key);
}

// key may carry a folder prefix ("sfx/hit") that only keys the caches; source = {dir, ext}.
function fetchBytes(key, source = audioData.music) {
  if (!bytes.has(key)) {
    const url = `${source.dir}${key.replace(/^sfx\//, '')}${source.ext}`;
    const promise = fetch(url)
      .then((res) => (res.ok && !/text\/html/.test(res.headers.get('content-type') || '') ? res.arrayBuffer() : null))
      .catch(() => null);
    bytes.set(key, promise);
  }
  return bytes.get(key);
}

// Downloads music files in the background, one after another (decoding waits for
// playMusic: it needs the unlocked AudioContext). With music.prefetchPolicy
// "next-step" the default is only music.bootPrefetch (the title); the chapter asks
// for each step's tracks itself (systems/MusicPlan.js prefetchMusicFor). Aliases
// resolve to their files; keys without a file (procedural) are skipped.
export async function prefetchMusic(keys) {
  const list = keys ?? (mcfg.prefetchPolicy === 'next-step' ? mcfg.bootPrefetch : mcfg.prefetch);
  audioLog({ ev: 'prefetch', keys: list });
  for (const key of list) {
    const id = resolveMusicKey(key);
    if (FILES.has(id)) await fetchBytes(id);
  }
}

// Frees the decoded audio (about 20-25 MB per minute of stereo) and the downloaded bytes
// of every music file that is not in `keys`, music.bootPrefetch or playing now. A file
// asked for again later is fetched again (the HTTP cache has it) and decoded on demand.
export function keepMusic(keys) {
  const keep = new Set([...mcfg.bootPrefetch, ...keys].map(resolveMusicKey));
  if (current) keep.add(current.id);
  if (oneShot) keep.add(oneShot.id);
  const dropped = [];
  for (const cache of [buffers, bytes]) {
    for (const id of [...cache.keys()]) {
      if (id.startsWith('sfx/') || keep.has(id)) continue;
      cache.delete(id);
      if (!dropped.includes(id)) dropped.push(id);
    }
  }
  audioLog({ ev: 'keep', keys: [...keep], dropped });
}

// Safari's decodeAudioData still wants callbacks. A file that isn't audio
// (e.g. a dev server's HTML fallback) decodes to null = silence.
function decode(data) {
  return new Promise((resolve) => {
    try {
      const p = ctx.decodeAudioData(data, resolve, () => resolve(null));
      if (p && p.catch) p.catch(() => resolve(null));
    } catch (err) {
      resolve(null);
    }
  });
}
